require: rubocop-rails
require: rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
  - "**/scripts/**/**/**/*"
  - "vendor/**/*"
  - "**/tmp/**/*"
  - "**/db/**/*"
  - "**/bin/**/*"
  - "**/node_modules/**/*"
  DisplayCopNames: true
  StyleGuideCopsOnly: false
